export const FETCH_METADATA_USER_CREDENTIALS =
  '@CORE.FETCH_METADATA_USER_CREDENTIALS'
export const FETCH_METADATA_USER_CREDENTIALS_LOADING =
  '@CORE.FETCH_METADATA_USER_CREDENTIALS_LOADING'
export const FETCH_METADATA_USER_CREDENTIALS_SUCCESS =
  '@CORE.FETCH_METADATA_USER_CREDENTIALS_SUCCESS'
export const FETCH_METADATA_USER_CREDENTIALS_FAILURE =
  '@CORE.FETCH_METADATA_USER_CREDENTIALS_FAILURE'

export const CREATE_METADATA_USER_CREDENTIALS =
  '@CORE.CREATE_METADATA_USER_CREDENTIALS'

export const SET_USER_CREDENTIALS = '@CORE.SET_USER_CREDENTIALS'
