export const FETCH_OPTIONS = '@CORE.FETCH_OPTIONS'
export const FETCH_OPTIONS_LOADING = '@CORE.FETCH_OPTIONS_LOADING'
export const FETCH_OPTIONS_SUCCESS = '@CORE.FETCH_OPTIONS_SUCCESS'
export const FETCH_OPTIONS_FAILURE = '@CORE.FETCH_OPTIONS_FAILURE'
