export const FETCH_WALLET_OPTIONS = '@CORE.FETCH_WALLET_OPTIONS'
export const FETCH_WALLET_OPTIONS_SUCCESS = '@CORE.FETCH_WALLET_OPTIONS_SUCCESS'
export const FETCH_WALLET_OPTIONS_ERROR = '@CORE.FETCH_WALLET_OPTIONS_ERROR'
