export const REFRESH = '@CORE.REFRESH'

export const REFRESH_SUCCESS = '@CORE.REFRESH_SUCCESS'
export const REFRESH_LOADING = '@CORE.REFRESH_LOADING'
export const REFRESH_FAILURE = '@CORE.REFRESH_FAILURE'
