

// reducers
export const ADD = '@LN.PEERS.ADD'
export const REMOVE = '@LN.PEERS.REMOVE'
export const CONNECTED = '@LN.PEER.CONNECTED'
export const DISCONNECTED = '@LN.PEER.DISCONNECTED'
export const PING_RECEIVED = '@LN.PEER.PING_RECEIVED'
export const INIT_MESSAGE_RECEIVED = '@LN.PEER.INIT_MESSAGE_RECEIVED'

// sagas
export const CONNECT = '@LN.PEER.CONNECT'
export const SEND_MESSAGE = '@LN.PEERS.SEND_MESSAGE'
export const DISCONNECT = '@LN.PEER.DISCONNECT'

//
// export const HANDSHAKE_COMPLETE = '@LN.PEERS.HANDSHAKE_COMPLETE'
//

