export const START_SOCKET = '@CORE.ETHEREUM.START_SOCKET'
export const STOP_SOCKET = '@CORE.ETHEREUM.STOP_SOCKET'

export const OPEN_SOCKET = '@CORE.ETHEREUM.OPEN_SOCKET'
export const MESSAGE_SOCKET = '@CORE.ETHEREUM.MESSAGE_SOCKET'
export const CLOSE_SOCKET = '@CORE.ETHEREUM.CLOSE_SOCKET'

export const PAYMENT_RECEIVED = '@CORE.WEBSOCKET.ETH_PAYMENT_RECEIVED'
