export const VERIFY_IDENTITY_TITLE = 'verify_identity_title'
export const VERIFY_IDENTITY_MSG = 'verify_identity_msg'
export const CONFIRM_VERIFY_IDENTITY = 'confirm_verify_identity'
export const CANCEL_VERIFY_IDENTITY = 'cancel_verify_identity'
export const PHONE_CALL_TITLE = 'phone_call_title'
export const PHONE_CALL_MSG = 'phone_call_msg'
export const CONFIRM_PHONE_CALL = 'confirm_phone_call'
export const CANCEL_PHONE_CALL = 'cancel_phone_call'
