export const FETCH_SETTINGS = '@CORE.FETCH_SETTINGS'
export const FETCH_SETTINGS_SUCCESS = '@CORE.FETCH_SETTINGS_SUCCESS'
export const FETCH_SETTINGS_ERROR = '@CORE.FETCH_SETTINGS_ERROR'

export const REQUEST_PAIRING_CODE = '@CORE.REQUEST_PAIRING_CODE'
export const REQUEST_PAIRING_CODE_SUCCESS = '@CORE.REQUEST_PAIRING_CODE_SUCCESS'
export const REQUEST_PAIRING_CODE_ERROR = '@CORE.REQUEST_PAIRING_CODE_ERROR'

export const UPDATE_EMAIL = '@CORE.UPDATE_EMAIL'
export const UPDATE_EMAIL_SUCCESS = '@CORE.UPDATE_EMAIL_SUCCESS'
export const UPDATE_EMAIL_ERROR = '@CORE.UPDATE_EMAIL_ERROR'

export const SEND_EMAIL_CONFIRMATION = '@CORE.SEND_EMAIL_CONFIRMATION'
export const SEND_EMAIL_CONFIRMATION_SUCCESS = '@CORE.SEND_EMAIL_CONFIRMATION_SUCCESS'
export const SEND_EMAIL_CONFIRMATION_ERROR = '@CORE.SEND_EMAIL_CONFIRMATION_ERROR'

export const VERIFY_EMAIL = '@CORE.VERIFY_EMAIL'
export const VERIFY_EMAIL_SUCCESS = '@CORE.VERIFY_EMAIL_SUCCESS'
export const VERIFY_EMAIL_ERROR = '@CORE.VERIFY_EMAIL_ERROR'

export const UPDATE_MOBILE = '@CORE.UPDATE_MOBILE'
export const UPDATE_MOBILE_SUCCESS = '@CORE.UPDATE_MOBILE_SUCCESS'
export const UPDATE_MOBILE_ERROR = '@CORE.UPDATE_MOBILE_ERROR'

export const VERIFY_MOBILE = '@CORE.VERIFY_MOBILE'
export const VERIFY_MOBILE_SUCCESS = '@CORE.VERIFY_MOBILE_SUCCESS'
export const VERIFY_MOBILE_ERROR = '@CORE.VERIFY_MOBILE_ERROR'

export const UPDATE_LANGUAGE = '@CORE.UPDATE_LANGUAGE'
export const UPDATE_LANGUAGE_SUCCESS = '@CORE.UPDATE_LANGUAGE_SUCCESS'
export const UPDATE_LANGUAGE_ERROR = '@CORE.UPDATE_LANGUAGE_ERROR'

export const UPDATE_CURRENCY = '@CORE.UPDATE_CURRENCY'
export const UPDATE_CURRENCY_SUCCESS = '@CORE.UPDATE_CURRENCY_SUCCESS'
export const UPDATE_CURRENCY_ERROR = '@CORE.UPDATE_CURRENCY_ERROR'

export const UPDATE_BITCOIN_UNIT = '@CORE.UPDATE_BITCOIN_UNIT'
export const UPDATE_BITCOIN_UNIT_SUCCESS = '@CORE.UPDATE_BITCOIN_UNIT_SUCCESS'
export const UPDATE_BITCOIN_UNIT_ERROR = '@CORE.UPDATE_BITCOIN_UNIT_ERROR'

export const UPDATE_AUTO_LOGOUT = '@CORE.UPDATE_AUTO_LOGOUT'
export const UPDATE_AUTO_LOGOUT_SUCCESS = '@CORE.UPDATE_AUTO_LOGOUT_SUCCESS'
export const UPDATE_AUTO_LOGOUT_ERROR = '@CORE.UPDATE_AUTO_LOGOUT_ERROR'

export const UPDATE_HINT = '@CORE.UPDATE_HINT'
export const UPDATE_HINT_SUCCESS = '@CORE.UPDATE_HINT_SUCCESS'
export const UPDATE_HINT_ERROR = '@CORE.UPDATE_HINT_ERROR'
