export const FETCH_SETTINGS = '@CORE.FETCH_SETTINGS'
export const FETCH_SETTINGS_SUCCESS = '@CORE.FETCH_SETTINGS_SUCCESS'
export const FETCH_SETTINGS_ERROR = '@CORE.FETCH_SETTINGS_ERROR'

export const REQUEST_PAIRING_CODE = '@CORE.REQUEST_PAIRING_CODE'
export const REQUEST_PAIRING_CODE_SUCCESS = '@CORE.REQUEST_PAIRING_CODE_SUCCESS'
export const REQUEST_PAIRING_CODE_ERROR = '@CORE.REQUEST_PAIRING_CODE_ERROR'

export const UPDATE_EMAIL = '@CORE.UPDATE_EMAIL'
export const UPDATE_EMAIL_SUCCESS = '@CORE.UPDATE_EMAIL_SUCCESS'
export const UPDATE_EMAIL_ERROR = '@CORE.UPDATE_EMAIL_ERROR'

export const SEND_EMAIL_CONFIRMATION = '@CORE.SEND_EMAIL_CONFIRMATION'
export const SEND_EMAIL_CONFIRMATION_SUCCESS = '@CORE.SEND_EMAIL_CONFIRMATION_SUCCESS'
export const SEND_EMAIL_CONFIRMATION_ERROR = '@CORE.SEND_EMAIL_CONFIRMATION_ERROR'

export const VERIFY_EMAIL = '@CORE.VERIFY_EMAIL'
export const VERIFY_EMAIL_SUCCESS = '@CORE.VERIFY_EMAIL_SUCCESS'
export const VERIFY_EMAIL_ERROR = '@CORE.VERIFY_EMAIL_ERROR'

export const UPDATE_MOBILE = '@CORE.UPDATE_MOBILE'
export const UPDATE_MOBILE_SUCCESS = '@CORE.UPDATE_MOBILE_SUCCESS'
export const UPDATE_MOBILE_ERROR = '@CORE.UPDATE_MOBILE_ERROR'

export const VERIFY_MOBILE = '@CORE.VERIFY_MOBILE'
export const VERIFY_MOBILE_SUCCESS = '@CORE.VERIFY_MOBILE_SUCCESS'
export const VERIFY_MOBILE_ERROR = '@CORE.VERIFY_MOBILE_ERROR'

export const UPDATE_LANGUAGE = '@CORE.UPDATE_LANGUAGE'
export const UPDATE_LANGUAGE_SUCCESS = '@CORE.UPDATE_LANGUAGE_SUCCESS'
export const UPDATE_LANGUAGE_ERROR = '@CORE.UPDATE_LANGUAGE_ERROR'

export const UPDATE_CURRENCY = '@CORE.UPDATE_CURRENCY'
export const UPDATE_CURRENCY_SUCCESS = '@CORE.UPDATE_CURRENCY_SUCCESS'
export const UPDATE_CURRENCY_ERROR = '@CORE.UPDATE_CURRENCY_ERROR'

export const UPDATE_BITCOIN_UNIT = '@CORE.UPDATE_BITCOIN_UNIT'
export const UPDATE_BITCOIN_UNIT_SUCCESS = '@CORE.UPDATE_BITCOIN_UNIT_SUCCESS'
export const UPDATE_BITCOIN_UNIT_ERROR = '@CORE.UPDATE_BITCOIN_UNIT_ERROR'

export const UPDATE_AUTO_LOGOUT = '@CORE.UPDATE_AUTO_LOGOUT'
export const UPDATE_AUTO_LOGOUT_SUCCESS = '@CORE.UPDATE_AUTO_LOGOUT_SUCCESS'
export const UPDATE_AUTO_LOGOUT_ERROR = '@CORE.UPDATE_AUTO_LOGOUT_ERROR'

export const UPDATE_LOGGING_LEVEL = '@CORE.UPDATE_LOGGING_LEVEL'
export const UPDATE_LOGGING_LEVEL_SUCCESS = '@CORE.UPDATE_LOGGING_LEVEL_SUCCESS'
export const UPDATE_LOGGING_LEVEL_ERROR = '@CORE.UPDATE_LOGGING_LEVEL_ERROR'

export const UPDATE_IP_LOCK = '@CORE.UPDATE_IP_LOCK'
export const UPDATE_IP_LOCK_SUCCESS = '@CORE.UPDATE_IP_LOCK_SUCCESS'
export const UPDATE_IP_LOCK_ERROR = '@CORE.UPDATE_IP_LOCK_ERROR'

export const UPDATE_IP_LOCK_ON = '@CORE.UPDATE_IP_LOCK_ON'
export const UPDATE_IP_LOCK_ON_SUCCESS = '@CORE.UPDATE_IP_LOCK_ON_SUCCESS'
export const UPDATE_IP_LOCK_ON_ERROR = '@CORE.UPDATE_IP_LOCK_ON_ERROR'

export const UPDATE_BLOCK_TOR_IPS = '@CORE.UPDATE_BLOCK_TOR_IPS'
export const UPDATE_BLOCK_TOR_IPS_SUCCESS = '@CORE.UPDATE_BLOCK_TOR_IPS_SUCCESS'
export const UPDATE_BLOCK_TOR_IPS_ERROR = '@CORE.UPDATE_BLOCK_TOR_IPS_ERROR'

export const UPDATE_HINT = '@CORE.UPDATE_HINT'
export const UPDATE_HINT_SUCCESS = '@CORE.UPDATE_HINT_SUCCESS'
export const UPDATE_HINT_ERROR = '@CORE.UPDATE_HINT_ERROR'

export const UPDATE_AUTH_TYPE = '@CORE.UPDATE_AUTH_TYPE'
export const UPDATE_AUTH_TYPE_SUCCESS = '@CORE.UPDATE_AUTH_TYPE_SUCCESS'
export const UPDATE_AUTH_TYPE_ERROR = '@CORE.UPDATE_AUTH_TYPE_ERROR'

export const UPDATE_AUTH_TYPE_NEVER_SAVE = '@CORE.UPDATE_AUTH_TYPE_NEVER_SAVE'
export const UPDATE_AUTH_TYPE_NEVER_SAVE_SUCCESS = '@CORE.UPDATE_AUTH_TYPE_NEVER_SAVE_SUCCESS'
export const UPDATE_AUTH_TYPE_NEVER_SAVE_ERROR = '@CORE.UPDATE_AUTH_TYPE_NEVER_SAVE_ERROR'

export const GET_GOOGLE_AUTHENTICATOR_SECRET_URL = '@CORE.GET_GOOGLE_AUTHENTICATOR_SECRET_URL'
export const GET_GOOGLE_AUTHENTICATOR_SECRET_URL_SUCCESS = '@CORE.GET_GOOGLE_AUTHENTICATOR_SECRET_URL_SUCCESS'
export const GET_GOOGLE_AUTHENTICATOR_SECRET_URL_ERROR = '@CORE.GET_GOOGLE_AUTHENTICATOR_SECRET_URL_ERROR'

export const CONFIRM_GOOGLE_AUTHENTICATOR_SETUP = '@CORE.CONFIRM_GOOGLE_AUTHENTICATOR_SETUP_URL'
export const CONFIRM_GOOGLE_AUTHENTICATOR_SETUP_SUCCESS = '@CORE.CONFIRM_GOOGLE_AUTHENTICATOR_SETUP_SUCCESS'
export const CONFIRM_GOOGLE_AUTHENTICATOR_SETUP_ERROR = '@CORE.CONFIRM_GOOGLE_AUTHENTICATOR_SETUP_ERROR'

export const ENABLE_YUBIKEY = '@CORE.ENABLE_YUBIKEY'
export const ENABLE_YUBIKEY_SUCCESS = '@CORE.ENABLE_YUBIKEY_SUCCESS'
export const ENABLE_YUBIKEY_ERROR = '@CORE.ENABLE_YUBIKEY_ERROR'
