export const FETCH_SETTINGS = '@CORE.FETCH_SETTINGS'
export const FETCH_SETTINGS_SUCCESS = '@CORE.FETCH_SETTINGS_SUCCESS'
export const FETCH_SETTINGS_ERROR = '@CORE.FETCH_SETTINGS_ERROR'

export const REQUEST_PAIRING_CODE = '@CORE.REQUEST_PAIRING_CODE'
export const REQUEST_PAIRING_CODE_SUCCESS = '@CORE.REQUEST_PAIRING_CODE_SUCCESS'
export const REQUEST_PAIRING_CODE_ERROR = '@CORE.REQUEST_PAIRING_CODE_ERROR'
