import { path } from 'ramda'
import { settingsPath } from '../paths'

export const getBtcUnit = path([settingsPath, 'btc_currency'])
export const getLanguage = path([settingsPath, 'language'])
export const getCountryCode = path([settingsPath, 'country_code'])
export const getCurrency = path([settingsPath, 'currency'])
export const getSmsNumber = path([settingsPath, 'sms_number'])
export const getSmsVerified = path([settingsPath, 'sms_verified'])
export const getEmail = path([settingsPath, 'email'])
export const getEmailVerified = path([settingsPath, 'email_verified'])
export const getAutoLogout = path([settingsPath, 'auto_logout'])
export const getLoggingLevel = path([settingsPath, 'logging_level'])
export const getIpLock = path([settingsPath, 'ip_lock'])
export const getIpLockOn = path([settingsPath, 'ip_lock_on'])
export const getBlockTorIps = path([settingsPath, 'block_tor_ips'])
export const getHint = path([settingsPath, 'password_hint1'])
export const getAuthType = path([settingsPath, 'auth_type'])
export const getAuthTypeNeverSave = path([settingsPath, 'never_save_auth_type'])
