
// FETCH_METADATA_ETHEREUM
export const FETCH_METADATA_ETHEREUM = '@CORE.FETCH_METADATA_ETHEREUM'
export const FETCH_METADATA_ETHEREUM_LOADING = '@CORE.FETCH_METADATA_ETHEREUM_LOADING'
export const FETCH_METADATA_ETHEREUM_SUCCESS = '@CORE.FETCH_METADATA_ETHEREUM_SUCCESS'
export const FETCH_METADATA_ETHEREUM_FAILURE = '@CORE.FETCH_METADATA_ETHEREUM_FAILURE'
