import { setTxNote } from '../../../types/Wallet'
import { SET_TRANSACTION_NOTE } from '../../wallet/actionTypes'

export const UPDATE_METADATA_ETHEREUM = '@CORE.KVSTORE.UPDATE_METADATA_ETHEREUM'

// FETCH_METADATA_ETHEREUM
export const FETCH_METADATA_ETHEREUM = '@CORE.FETCH_METADATA_ETHEREUM'
export const FETCH_METADATA_ETHEREUM_LOADING = '@CORE.FETCH_METADATA_ETHEREUM_LOADING'
export const FETCH_METADATA_ETHEREUM_SUCCESS = '@CORE.FETCH_METADATA_ETHEREUM_SUCCESS'
export const FETCH_METADATA_ETHEREUM_FAILURE = '@CORE.FETCH_METADATA_ETHEREUM_FAILURE'

export const CREATE_METADATA_ETHEREUM = '@CORE.CREATE_METADATA_ETHEREUM'

export const SET_TRANSACTION_NOTE_ETHEREUM = '@CORE.SET_TRANSACTION_NOTE_ETHEREUM'
