// CREATE
export const CREATE_METADATA_UNIFIED_CREDENTIALS = '@CORE.CREATE_METADATA_UNIFIED_CREDENTIALS'

// FETCH
export const FETCH_METADATA_UNIFIED_CREDENTIALS = '@CORE.FETCH_METADATA_UNIFIED_CREDENTIALS'
export const FETCH_METADATA_UNIFIED_CREDENTIALS_LOADING =
  '@CORE.FETCH_METADATA_UNIFIED_CREDENTIALS_LOADING'
export const FETCH_METADATA_UNIFIED_CREDENTIALS_SUCCESS =
  '@CORE.FETCH_METADATA_UNIFIED_CREDENTIALS_SUCCESS'
export const FETCH_METADATA_UNIFIED_CREDENTIALS_FAILURE =
  '@CORE.FETCH_METADATA_UNIFIED_CREDENTIALS_FAILURE'

// SET/UPDATE
export const SET_UNIFIED_CREDENTIALS = '@CORE.SET_UNIFIED_CREDENTIALS'
