export const SET_WHATS_NEW = '@CORE.KVSTORE.SET_WHATS_NEW'

export const UPDATE_WHATS_NEW = '@CORE.KVSTORE.UPDATE_WHATS_NEW'

// FETCH_METADATA_WHATSNEW
export const FETCH_METADATA_WHATSNEW = '@CORE.FETCH_METADATA_WHATSNEW'
export const FETCH_METADATA_WHATSNEW_LOADING = '@CORE.FETCH_METADATA_WHATSNEW_LOADING'
export const FETCH_METADATA_WHATSNEW_SUCCESS = '@CORE.FETCH_METADATA_WHATSNEW_SUCCESS'
export const FETCH_METADATA_WHATSNEW_ERROR = '@CORE.FETCH_METADATA_WHATSNEW_ERROR'
