
export const UPDATE_METADATA_WHATSNEW = '@CORE.KVSTORE.UPDATE_METADATA_WHATSNEW'

// FETCH_METADATA_WHATSNEW
export const FETCH_METADATA_WHATSNEW = '@CORE.FETCH_METADATA_WHATSNEW'
export const FETCH_METADATA_WHATSNEW_LOADING = '@CORE.FETCH_METADATA_WHATSNEW_LOADING'
export const FETCH_METADATA_WHATSNEW_SUCCESS = '@CORE.FETCH_METADATA_WHATSNEW_SUCCESS'
export const FETCH_METADATA_WHATSNEW_FAILURE = '@CORE.FETCH_METADATA_WHATSNEW_FAILURE'

export const CREATE_METADATA_WHATSNEW = '@CORE.CREATE_METADATA_WHATSNEW'
