
export const SET_TRADES_BUYSELL = '@CORE.SET_TRADES_BUYSELL'
export const UPDATE_METADATA_BUYSELL = '@CORE.UPDATE_METADATA_BUYSELL'
// FETCH_METADATA_BUYSELL
export const FETCH_METADATA_BUYSELL = '@CORE.FETCH_METADATA_BUYSELL'
export const FETCH_METADATA_BUYSELL_LOADING = '@CORE.FETCH_METADATA_BUYSELL_LOADING'
export const FETCH_METADATA_BUYSELL_SUCCESS = '@CORE.FETCH_METADATA_BUYSELL_SUCCESS'
export const FETCH_METADATA_BUYSELL_FAILURE = '@CORE.FETCH_METADATA_BUYSELL_FAILURE'

export const CREATE_METADATA_BUYSELL = '@CORE.CREATE_METADATA_BUYSELL'

export const SET_PROFILE_BUYSELL = '@CORE.SET_PROFILE_BUYSELL'
