
export const SET_SFOX_TRADES_BUYSELL = '@CORE.SET_SFOX_TRADES_BUYSELL'
export const UPDATE_METADATA_BUYSELL = '@CORE.UPDATE_METADATA_BUYSELL'

export const SET_COINIFY_TRADES_BUYSELL = '@CORE.SET_COINIFY_TRADES_BUYSELL'
// FETCH_METADATA_BUYSELL
export const FETCH_METADATA_BUYSELL = '@CORE.FETCH_METADATA_BUYSELL'
export const FETCH_METADATA_BUYSELL_LOADING = '@CORE.FETCH_METADATA_BUYSELL_LOADING'
export const FETCH_METADATA_BUYSELL_SUCCESS = '@CORE.FETCH_METADATA_BUYSELL_SUCCESS'
export const FETCH_METADATA_BUYSELL_FAILURE = '@CORE.FETCH_METADATA_BUYSELL_FAILURE'

export const CREATE_METADATA_BUYSELL = '@CORE.CREATE_METADATA_BUYSELL'

export const SFOX_SET_PROFILE_BUYSELL = '@CORE.SFOX_SET_PROFILE_BUYSELL'
export const COINIFY_SET_PROFILE_BUYSELL = '@CORE.COINIFY_SET_PROFILE_BUYSELL'

export const WIPE_EXTERNAL = '@CORE.WIPE_EXTERNAL'
export const WIPE_EXTERNAL_SFOX = '@CORE.WIPE_EXTERNAL_SFOX'
