// METADATA
export const CREATE_METADATA_BUYSELL = '@CORE.CREATE_METADATA_BUYSELL'
export const FETCH_METADATA_BUYSELL = '@CORE.FETCH_METADATA_BUYSELL'
export const FETCH_METADATA_BUYSELL_LOADING =
  '@CORE.FETCH_METADATA_BUYSELL_LOADING'
export const FETCH_METADATA_BUYSELL_SUCCESS =
  '@CORE.FETCH_METADATA_BUYSELL_SUCCESS'
export const FETCH_METADATA_BUYSELL_FAILURE =
  '@CORE.FETCH_METADATA_BUYSELL_FAILURE'
export const UPDATE_METADATA_BUYSELL = '@CORE.UPDATE_METADATA_BUYSELL'
export const WIPE_EXTERNAL = '@CORE.WIPE_EXTERNAL'
