
export const EXCHANGE_INITIALIZED = '@EVENT.EXCHANGE_INITIALIZED'

export const EXCHANGE_SWAP_CLICKED = '@EVENT.EXCHANGE_SWAP_CLICKED'

export const EXCHANGE_SUBMIT_CLICKED = '@EVENT.EXCHANGE_SUBMIT_CLICKED'

export const EXCHANGE_MINIMUM_CLICKED = '@EVENT.EXCHANGE_MINIMUM_CLICKED'

export const EXCHANGE_MAXIMUM_CLICKED = '@EVENT.EXCHANGE_MAXIMUM_CLICKED'
