
export const EXCHANGE_INITIALIZED = '@EVENT.EXCHANGE_INITIALIZED'

export const EXCHANGE_DESTROYED = '@EVENT.EXCHANGE_DESTROYED'

export const EXCHANGE_FIRST_STEP_INITIALIZED = '@EVENT.EXCHANGE_FIRST_STEP_INITIALIZED'

export const EXCHANGE_FIRST_STEP_LOADING = '@EVENT.EXCHANGE_FIRST_STEP_LOADING'

export const EXCHANGE_FIRST_STEP_LOADED = '@EVENT.EXCHANGE_FIRST_STEP_LOADED'

export const EXCHANGE_FIRST_STEP_ERROR = '@EVENT.EXCHANGE_FIRST_STEP_ERROR'

export const EXCHANGE_FIRST_STEP_SUBMIT_CLICKED = '@EVENT.EXCHANGE_FIRST_STEP_SUBMIT_CLICKED'

export const EXCHANGE_FIRST_STEP_SWAP_CLICKED = '@EVENT.EXCHANGE_FIRST_STEP_SWAP_CLICKED'

export const EXCHANGE_FIRST_STEP_MINIMUM_CLICKED = '@EVENT.EXCHANGE_FIRST_STEP_MINIMUM_CLICKED'

export const EXCHANGE_FIRST_STEP_MAXIMUM_CLICKED = '@EVENT.EXCHANGE_FIRST_STEP_MAXIMUM_CLICKED'

export const EXCHANGE_SECOND_STEP_INITIALIZED = '@EVENT.EXCHANGE_SECOND_STEP_INITIALIZED'

export const EXCHANGE_SECOND_STEP_SUCCESS = '@EVENT.EXCHANGE_SECOND_STEP_SUCCESS'

export const EXCHANGE_SECOND_STEP_FAILURE = '@EVENT.EXCHANGE_SECOND_STEP_FAILURE'

export const EXCHANGE_SECOND_STEP_CANCEL_CLICKED = '@EVENT.EXCHANGE_SECOND_STEP_CANCEL_CLICKED'

export const EXCHANGE_SECOND_STEP_SUBMIT_CLICKED = '@EVENT.EXCHANGE_SECOND_STEP_SUBMIT_CLICKED'

export const EXCHANGE_SECOND_STEP_ORDER_EXPIRED = '@EVENT.EXCHANGE_SECOND_STEP_ORDER_EXPIRED'

export const EXCHANGE_THIRD_STEP_INITIALIZED = '@EVENT.EXCHANGE_THIRD_STEP_INITIALIZED'

export const EXCHANGE_THIRD_STEP_CLOSE_CLICKED = '@EVENT.EXCHANGE_THIRD_STEP_CLOSE_CLICKED'
