import React from 'react'
import styled from 'styled-components'
import { FormattedMessage } from 'react-intl'
import { Banner } from 'blockchain-info-components'

const Wrapper = styled.div`
  margin-top: 15px;
`
const Info = styled.div`
  margin-top: 15px;
  font-size: 12px;
`

class ImportInternalBitcoinAddress extends React.Component {
  render () {
    return (
      <Wrapper>
        <Banner type='warning'>
          <FormattedMessage id='modals.importbtcaddress.import_internal_bitcoin_address.warning' defaultMessage='Addresses generated by this wallet should not be imported.' />
        </Banner>
        <Info>
          <FormattedMessage id='modals.importbtcaddress.import.info' defaultMessage='Your wallet automatically creates new bitcoin addresses as it needs them. You can optionally import an existing address generated outside of this wallet and transfer the funds to your wallet if you have the corresponding Private Key.' />
        </Info>
      </Wrapper>
    )
  }
}

export default ImportInternalBitcoinAddress
