export type FlyoutE2EType =
  | 'borrowModal'
  | 'faqModal'
  | 'interestModal'
  | 'recoveryPhraseModal'
  | 'simpleBuyModal'
  | 'welcomeModal'
  | 'withdrawalModal'
  | 'custodyWithdrawModal'
  | 'infoModalLinkFromExchangeAccount'
