// FETCH_METADATA_CONTACTS
export const FETCH_METADATA_CONTACTS = '@CORE.FETCH_METADATA_CONTACTS'
export const FETCH_METADATA_CONTACTS_LOADING = '@CORE.FETCH_METADATA_CONTACTS_LOADING'
export const FETCH_METADATA_CONTACTS_SUCCESS = '@CORE.FETCH_METADATA_CONTACTS_SUCCESS'
export const FETCH_METADATA_CONTACTS_FAILURE = '@CORE.FETCH_METADATA_CONTACTS_FAILURE'

export const CREATE_METADATA_CONTACTS = '@CORE.CREATE_METADATA_CONTACTS'
