// FETCH_METADATA_CONTACTS
export const FETCH_METADATA_CONTACTS = '@CORE.FETCH_METADATA_CONTACTS'
export const FETCH_METADATA_CONTACTS_LOADING = '@CORE.FETCH_METADATA_CONTACTS_LOADING'
export const FETCH_METADATA_CONTACTS_SUCCESS = '@CORE.FETCH_METADATA_CONTACTS_SUCCESS'
export const FETCH_METADATA_CONTACTS_ERROR = '@CORE.FETCH_METADATA_CONTACTS_ERROR'
