'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var PRICE_INDEX_SERIES_INITIALIZED = exports.PRICE_INDEX_SERIES_INITIALIZED = '@EVENT.PRICE_INDEX_SERIES_INITIALIZED';

var PRICE_INDEX_SERIES_TIME_CLICKED = exports.PRICE_INDEX_SERIES_TIME_CLICKED = '@EVENT.PRICE_INDEX_SERIES_TIME_CLICKED';

var PRICE_INDEX_SERIES_COIN_CLICKED = exports.PRICE_INDEX_SERIES_COIN_CLICKED = '@EVENT.PRICE_INDEX_SERIES_COIN_CLICKED';