// export const SET_SHAPESHIFT = '@CORE.KVSTORE.SET_SHAPESHIFT'

// FETCH_METADATA_SHAPESHIFT
export const FETCH_METADATA_SHAPESHIFT = '@CORE.FETCH_METADATA_SHAPESHIFT'
export const FETCH_METADATA_SHAPESHIFT_LOADING = '@CORE.FETCH_METADATA_SHAPESHIFT_LOADING'
export const FETCH_METADATA_SHAPESHIFT_SUCCESS = '@CORE.FETCH_METADATA_SHAPESHIFT_SUCCESS'
export const FETCH_METADATA_SHAPESHIFT_FAILURE = '@CORE.FETCH_METADATA_SHAPESHIFT_FAILURE'

export const CREATE_METADATA_SHAPESHIFT = '@CORE.CREATE_METADATA_SHAPESHIFT'
