export const START_SOCKET = '@CORE.BCH.START_SOCKET'
export const STOP_SOCKET = '@CORE.BCH.STOP_SOCKET'

export const OPEN_SOCKET = '@CORE.BCH.OPEN_SOCKET'
export const MESSAGE_SOCKET = '@CORE.BCH.MESSAGE_SOCKET'
export const CLOSE_SOCKET = '@CORE.BCH.CLOSE_SOCKET'

export const BCH_PAYMENT_RECEIVED = '@CORE.WEBSOCKET.BCH_PAYMENT_RECEIVED'
