// second Password
export const TOGGLE_SECOND_PASSWORD = '@CORE.TOGGLE_SECOND_PASSWORD'
export const TOGGLE_SECOND_PASSWORD_SUCCESS = '@CORE.TOGGLE_SECOND_PASSWORD_SUCCESS'
export const TOGGLE_SECOND_PASSWORD_ERROR = '@CORE.TOGGLE_SECOND_PASSWORD_ERROR'

export const CHANGE_SECOND_PASSWORD = '@CORE.CHANGE_SECOND_PASSWORD'
export const CHANGE_SECOND_PASSWORD_SUCCESS = '@CORE.CHANGE_SECOND_PASSWORD_SUCCESS'
export const CHANGE_SECOND_PASSWORD_ERROR = '@CORE.CHANGE_SECOND_PASSWORD_ERROR'

// change pbkdf2 iterations
export const SET_PBKDF2_ITERATIONS = '@CORE.SET_PBKDF2_ITERATIONS'
export const SET_PBKDF2_ITERATIONS_SUCCESS = '@CORE.SET_PBKDF2_ITERATIONS_SUCCESS'
export const SET_PBKDF2_ITERATIONS_ERROR = '@CORE.SET_PBKDF2_ITERATIONS_ERROR'

// legacy addresses addition
export const CREATE_LEGACY_ADDRESS = '@CORE.CREATE_LEGACY_ADDRESS'
export const CREATE_LEGACY_ADDRESS_SUCCESS = '@CORE.CREATE_LEGACY_ADDRESS_SUCCESS'
export const CREATE_LEGACY_ADDRESS_ERROR = '@CORE.CREATE_LEGACY_ADDRESS_ERROR'

// setters
export const SET_WRAPPER = '@CORE.SET_WRAPPER'
export const SET_MAIN_PASSWORD = '@CORE.SET_MAIN_PASSWORD'
export const SET_PAYLOAD_CHECKSUM = '@CORE.SET_PAYLOAD_CHECKSUM'
export const SET_LEGACY_ADDRESS_LABEL = '@CORE.SET_LEGACY_ADDRESS_LABEL'
export const SET_HD_ADDRESS_LABEL = '@CORE.SET_HD_ADDRESS_LABEL'

// deletes
export const DELETE_WRAPPER = '@CORE.DELETE_WRAPPER'
export const DELETE_LEGACY_ADDRESS = '@CORE.DELETE_LEGACY_ADDRESS'
export const DELETE_HD_ADDRESS_LABEL = '@CORE.DELETE_HD_ADDRESS_LABEL'

// autologout time
export const SET_AUTOLOGOUT = '@CORE.SET_AUTOLOGOUT'

// mnemonic verified
export const VERIFY_MNEMONIC = '@CORE.VERIFY_MNEMONIC'
