// setters
export const SET_WRAPPER = '@CORE.SET_WRAPPER'
export const REFRESH_WRAPPER = '@CORE.REFRESH_WRAPPER'
export const SET_MAIN_PASSWORD = '@CORE.SET_MAIN_PASSWORD'
export const SET_PAYLOAD_CHECKSUM = '@CORE.SET_PAYLOAD_CHECKSUM'
export const SET_LEGACY_ADDRESS_LABEL = '@CORE.SET_LEGACY_ADDRESS_LABEL'
export const SET_HD_ADDRESS_LABEL = '@CORE.SET_HD_ADDRESS_LABEL'
export const CREATE_LEGACY_ADDRESS = '@CORE.CREATE_LEGACY_ADDRESS'
export const SET_ACCOUNT_LABEL = '@CORE.SET_ACCOUNT_LABEL'
export const SET_ACCOUNT_ARCHIVED = '@CORE.SET_ACCOUNT_ARCHIVED'
export const SET_DEFAULT_ACCOUNT = '@CORE.SET_DEFAULT_ACCOUNT'
export const SET_ADDRESS_ARCHIVED = '@CORE.SET_ADDRESS_ARCHIVED'
export const SET_TRANSACTION_NOTE = '@CORE.SET_TRANSACTION_NOTE'
export const SET_SYNC_PUB_KEYS = '@CORE.SET_SYNC_PUB_KEYS'

// deletes
export const DELETE_WRAPPER = '@CORE.DELETE_WRAPPER'
export const DELETE_LEGACY_ADDRESS = '@CORE.DELETE_LEGACY_ADDRESS'
export const DELETE_HD_ADDRESS_LABEL = '@CORE.DELETE_HD_ADDRESS_LABEL'

// autologout time
export const SET_AUTOLOGOUT = '@CORE.SET_AUTOLOGOUT'

// mnemonic verified
export const VERIFY_MNEMONIC = '@CORE.VERIFY_MNEMONIC'

// check/update account labels
export const CHECK_UPDATE_ACCT_LABELS = '@CORE.CHECK_UPDATE_ACCT_LABELS'
