// wallet signup
export const CREATE_WALLET = '@CORE.CREATE_WALLET'
export const CREATE_WALLET_SUCCESS = '@CORE.CREATE_WALLET_SUCCESS'
export const CREATE_WALLET_ERROR = '@CORE.CREATE_WALLET_ERROR'

// second Password
export const TOGGLE_SECOND_PASSWORD = '@CORE.TOGGLE_SECOND_PASSWORD'
export const TOGGLE_SECOND_PASSWORD_SUCCESS = '@CORE.TOGGLE_SECOND_PASSWORD_SUCCESS'
export const TOGGLE_SECOND_PASSWORD_ERROR = '@CORE.TOGGLE_SECOND_PASSWORD_ERROR'

// legacy addresses addition
export const CREATE_LEGACY_ADDRESS = '@CORE.CREATE_LEGACY_ADDRESS'
export const CREATE_LEGACY_ADDRESS_SUCCESS = '@CORE.CREATE_LEGACY_ADDRESS_SUCCESS'
export const CREATE_LEGACY_ADDRESS_ERROR = '@CORE.CREATE_LEGACY_ADDRESS_ERROR'

// socket middleware
export const OPEN_SOCKET = '@CORE.OPEN_SOCKET'
export const MESSAGE_SOCKET = '@CORE.MESSAGE_SOCKET'
export const CLOSE_SOCKET = '@CORE.CLOSE_SOCKET'

// walletSync middleware
export const SYNC = '@CORE.SYNC'
export const SYNC_SUCCESS = '@CORE.SYNC_SUCCESS'
export const SYNC_ERROR = '@CORE.SYNC_ERROR'

// setters
export const SET_WRAPPER = '@CORE.SET_WRAPPER'
export const SET_MAIN_PASSWORD = '@CORE.SET_MAIN_PASSWORD'
export const SET_PAYLOAD_CHECKSUM = '@CORE.SET_PAYLOAD_CHECKSUM'
export const SET_LEGACY_ADDRESS_LABEL = '@CORE.SET_LEGACY_ADDRESS_LABEL'
export const SET_HD_ADDRESS_LABEL = '@CORE.SET_HD_ADDRESS_LABEL'

// deletes
export const DELETE_WRAPPER = '@CORE.DELETE_WRAPPER'
export const DELETE_LEGACY_ADDRESS = '@CORE.DELETE_LEGACY_ADDRESS'
export const DELETE_HD_ADDRESS_LABEL = '@CORE.DELETE_HD_ADDRESS_LABEL'
