export const ADDRESS_ADD = '@v3.ADDRESS_ADD'
export const ADDRESS_LABEL = '@v3.ADDRESS_LABEL'
export const WALLET_REPLACE = '@v3.WALLET_REPLACE'
export const WALLET_CLEAR = '@v3.WALLET_CLEAR'
export const SECOND_PASSWORD_ON = '@v3.SECOND_PASSWORD_ON'
export const SECOND_PASSWORD_OFF = '@v3.SECOND_PASSWORD_OFF'
export const MAIN_PASSWORD_CHANGE = '@v3.MAIN_PASSWORD_CHANGE'
export const SET_PAYLOAD_CHECKSUM = '@v3.SET_PAYLOAD_CHECKSUM'

export const WALLET_NEW = '@v3.WALLET_NEW'
export const WALLET_NEW_FAILURE = '@v3.WALLET_NEW_FAILURE'
export const WALLET_NEW_SUCCESS = '@v3.WALLET_NEW_SUCCESS'
export const WALLET_NEW_SET = '@v3.WALLET_NEW_SET'

export const REQUEST_SECOND_PASSWORD_TOGGLE = '@v3.REQUEST_SECOND_PASSWORD_TOGGLE'
export const HD_ADDRESS_LABEL_SET = '@v3.HD_ADDRESS_LABEL_SET'
export const HD_ADDRESS_LABEL_REMOVE = '@v3.HD_ADDRESS_LABEL_REMOVE'

// socket middleware
export const SOCKET_OPEN = '@v3.SOCKET_OPEN'
export const SOCKET_MESSAGE = '@v3.SOCKET_MESSAGE'
export const SOCKET_CLOSE = '@v3.SOCKET_CLOSE'

// walletSync middleware
export const SYNC_START = '@v3.SYNC_START'
export const SYNC_SUCCESS = '@v3.SYNC_SUCCESS'
export const SYNC_ERROR = '@v3.SYNC_ERROR'
