export enum TIER_TYPES {
  NONE = 0,
  SILVER = 1,
  GOLD = 2,
  SILVER_PLUS = 3
}

export enum SETTINGS_ITEMS {
  BUY_AND_DEPOSIT_WITH_BANK = 'BUY_AND_DEPOSIT_WITH_BANK',
  BUY_AND_SELL = 'BUY_AND_SELL',
  BUY_WITH_CARD = 'BUY_WITH_CARD',
  RECEIVE_CRYPTO = 'RECEIVE_CRYPTO',
  SAVINGS_INTEREST = 'SAVINGS_INTEREST',
  SEND_CRYPTO = 'SEND_CRYPTO',
  SWAP_CRYPTO = 'SWAP_CRYPTO',
  WITHDRAW_WITH_BANK = 'WITHDRAW_WITH_BANK'
}

export enum SETTINGS_ITEM_PERIOD {
  DAY = 'DAY',
  MONTH = 'MONTH',
  YEAR = 'YEAR'
}

export enum SETTINGS_ITEMS_ICONS {
  BUY_AND_DEPOSIT_WITH_BANK = 'bank-empty',
  BUY_AND_SELL = 'sell',
  BUY_WITH_CARD = 'credit-card',
  RECEIVE_CRYPTO = 'qr-code',
  SAVINGS_INTEREST = 'interest',
  SEND_CRYPTO = 'send-crypto',
  SWAP_CRYPTO = 'swap',
  WITHDRAW_WITH_BANK = 'bank-empty'
}
