// FETCH_METADATA_BCH
export const FETCH_METADATA_BCH = '@CORE.FETCH_METADATA_BCH'
export const FETCH_METADATA_BCH_LOADING = '@CORE.FETCH_METADATA_BCH_LOADING'
export const FETCH_METADATA_BCH_SUCCESS = '@CORE.FETCH_METADATA_BCH_SUCCESS'
export const FETCH_METADATA_BCH_FAILURE = '@CORE.FETCH_METADATA_BCH_FAILURE'

export const CREATE_METADATA_BCH = '@CORE.CREATE_METADATA_BCH'

export const IMPORT_LEGACY_ADDR_BCH = '@CORE.IMPORT_LEGACY_ADDR_BCH'
export const SET_LEGACY_ADDR_BCH = '@CORE.SET_LEGACY_ADDR_BCH'

export const SET_BCH_ACCOUNT_LABEL = '@CORE.SET_BCH_ACCOUNT_LABEL'
export const SET_BCH_ACCOUNT_ARCHIVED = '@CORE.SET_BCH_ACCOUNT_ARCHIVED'
export const SET_DEFAULT_BCH_ACCOUNT = '@CORE.SET_DEFAULT_BCH_ACCOUNT'
export const SET_TRANSACTION_NOTE_BCH = '@CORE.SET_TRANSACTION_NOTE_BCH'
