
// FETCH_METADATA_BCH
export const FETCH_METADATA_BCH = '@CORE.FETCH_METADATA_BCH'
export const FETCH_METADATA_BCH_LOADING = '@CORE.FETCH_METADATA_BCH_LOADING'
export const FETCH_METADATA_BCH_SUCCESS = '@CORE.FETCH_METADATA_BCH_SUCCESS'
export const FETCH_METADATA_BCH_FAILURE = '@CORE.FETCH_METADATA_BCH_FAILURE'

export const CREATE_METADATA_BCH = '@CORE.CREATE_METADATA_BCH'
