export const ROOT_URL = 'https://blockchain.info/'
export const API_BLOCKCHAIN_INFO = 'https://api.blockchain.info/'
export const API_CODE = '1770d5d9-bcea-4d28-ad21-6cbd5be018a8'
export const BLOCKCHAIN_DATA_PATH = 'blockchainData'
export const WALLET_IMMUTABLE_PATH = 'walletPayload'
