enum ADD_CARD_ERROR {
  NO_BIN = 'NO_BIN',
  NO_CVV = 'NO_CVV',
  NO_DEEP_LINK_URL = 'NO_DEEP_LINK_URL',
  NO_PAYMENT_METHOD_TOKENS = 'NO_PAYMENT_METHOD_TOKENS',
  NO_SCHEME = 'NO_SCHEME',
  NO_STATUS = 'NO_STATUS'
}

enum IFRAME_ACTION {
  ADD_CARD = 'ADD_CARD',
  ADD_CVV = 'ADD_CVV',
  BIN_CHANGED = 'BIN_CHANGED',
  CHANGE_BILLING_ADDRESS = 'CHANGE_BILLING_ADDRESS',
  DEEP_LINK = 'DEEP_LINK',
  REQUEST_BILLING_ADDRESS = 'REQUEST_BILLING_ADDRESS'
}

export { ADD_CARD_ERROR, IFRAME_ACTION }
