export { default as CheckBoxInput } from './CheckBoxInput'
export { default as HiddenInput } from './HiddenInput'
export { default as NumberInput } from './NumberInput'
export { default as PasswordInput } from './PasswordInput'
export { default as TextAreaInput } from './TextAreaInput'
export { default as TextInput } from './TextInput'
