// FETCH
export const FETCH_METADATA_WALLET_CREDENTIALS =
  '@CORE.FETCH_METADATA_WALLET_CREDENTIALS'
export const FETCH_METADATA_WALLET_CREDENTIALS_LOADING =
  '@CORE.FETCH_METADATA_WALLET_CREDENTIALS_LOADING'
export const FETCH_METADATA_WALLET_CREDENTIALS_SUCCESS =
  '@CORE.FETCH_METADATA_WALLET_CREDENTIALS_SUCCESS'
export const FETCH_METADATA_WALLET_CREDENTIALS_FAILURE =
  '@CORE.FETCH_METADATA_WALLET_CREDENTIALS_FAILURE'

// CREATE/UPDATE
export const UPDATE_METADATA_WALLET_CREDENTIALS =
  '@CORE.KVSTORE.UPDATE_METADATA_WALLET_CREDENTIALS'
export const CREATE_METADATA_WALLET_CREDENTIALS =
  '@CORE.CREATE_METADATA_WALLET_CREDENTIALS'

// SET/RESTORE
export const SET_WALLET_CREDENTIALS = '@CORE.SET_WALLET_CREDENTIALS'
export const RESTORE_WALLET_CREDENTIALS = '@CORE.RESTORE_WALLET_CREDENTIALS'
