// flow-typed signature: 25f9b54c059a2c73c3190d55d240a615
// flow-typed version: <<STUB>>/bech32_v^1.1.3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bech32'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bech32' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'bech32/index' {
  declare module.exports: $Exports<'bech32'>;
}
declare module 'bech32/index.js' {
  declare module.exports: $Exports<'bech32'>;
}
