// flow-typed signature: ef641ff6e4c8a3e25b7c6f513b50a774
// flow-typed version: <<STUB>>/big-rational_v^0.10.7/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'big-rational'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'big-rational' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'big-rational/BigInt_BigRat.min' {
  declare module.exports: any;
}

declare module 'big-rational/BigRational' {
  declare module.exports: any;
}

declare module 'big-rational/BigRational.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'big-rational/BigInt_BigRat.min.js' {
  declare module.exports: $Exports<'big-rational/BigInt_BigRat.min'>;
}
declare module 'big-rational/BigRational.js' {
  declare module.exports: $Exports<'big-rational/BigRational'>;
}
declare module 'big-rational/BigRational.min.js' {
  declare module.exports: $Exports<'big-rational/BigRational.min'>;
}
