// flow-typed signature: a54c63b1ab10109acc48aa83b638465b
// flow-typed version: <<STUB>>/bip39_v^2.3.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bip39'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bip39' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bip39/test/index' {
  declare module.exports: any;
}

declare module 'bip39/test/readme' {
  declare module.exports: any;
}

declare module 'bip39/util/wordlists' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bip39/index' {
  declare module.exports: $Exports<'bip39'>;
}
declare module 'bip39/index.js' {
  declare module.exports: $Exports<'bip39'>;
}
declare module 'bip39/test/index.js' {
  declare module.exports: $Exports<'bip39/test/index'>;
}
declare module 'bip39/test/readme.js' {
  declare module.exports: $Exports<'bip39/test/readme'>;
}
declare module 'bip39/util/wordlists.js' {
  declare module.exports: $Exports<'bip39/util/wordlists'>;
}
