// flow-typed signature: afa570c415591aeff40302c0d6ce1483
// flow-typed version: <<STUB>>/bitcoinjs-lib_v^3.1.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bitcoinjs-lib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bitcoinjs-lib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bitcoinjs-lib/src/address' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/block' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/bufferutils' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/crypto' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/ecdsa' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/ecpair' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/ecsignature' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/hdnode' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/index' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/networks' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/script_number' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/script' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/index' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/multisig/index' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/multisig/input' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/multisig/output' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/nulldata' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/pubkey/index' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/pubkey/input' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/pubkey/output' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/pubkeyhash/index' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/pubkeyhash/input' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/pubkeyhash/output' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/scripthash/index' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/scripthash/input' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/scripthash/output' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/witnesscommitment/index' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/witnesscommitment/output' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/witnesspubkeyhash/index' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/witnesspubkeyhash/input' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/witnesspubkeyhash/output' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/witnessscripthash/index' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/witnessscripthash/input' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/templates/witnessscripthash/output' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/transaction_builder' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/transaction' {
  declare module.exports: any;
}

declare module 'bitcoinjs-lib/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bitcoinjs-lib/src/address.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/address'>;
}
declare module 'bitcoinjs-lib/src/block.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/block'>;
}
declare module 'bitcoinjs-lib/src/bufferutils.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/bufferutils'>;
}
declare module 'bitcoinjs-lib/src/crypto.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/crypto'>;
}
declare module 'bitcoinjs-lib/src/ecdsa.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/ecdsa'>;
}
declare module 'bitcoinjs-lib/src/ecpair.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/ecpair'>;
}
declare module 'bitcoinjs-lib/src/ecsignature.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/ecsignature'>;
}
declare module 'bitcoinjs-lib/src/hdnode.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/hdnode'>;
}
declare module 'bitcoinjs-lib/src/index.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/index'>;
}
declare module 'bitcoinjs-lib/src/networks.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/networks'>;
}
declare module 'bitcoinjs-lib/src/script_number.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/script_number'>;
}
declare module 'bitcoinjs-lib/src/script.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/script'>;
}
declare module 'bitcoinjs-lib/src/templates/index.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/index'>;
}
declare module 'bitcoinjs-lib/src/templates/multisig/index.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/multisig/index'>;
}
declare module 'bitcoinjs-lib/src/templates/multisig/input.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/multisig/input'>;
}
declare module 'bitcoinjs-lib/src/templates/multisig/output.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/multisig/output'>;
}
declare module 'bitcoinjs-lib/src/templates/nulldata.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/nulldata'>;
}
declare module 'bitcoinjs-lib/src/templates/pubkey/index.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/pubkey/index'>;
}
declare module 'bitcoinjs-lib/src/templates/pubkey/input.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/pubkey/input'>;
}
declare module 'bitcoinjs-lib/src/templates/pubkey/output.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/pubkey/output'>;
}
declare module 'bitcoinjs-lib/src/templates/pubkeyhash/index.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/pubkeyhash/index'>;
}
declare module 'bitcoinjs-lib/src/templates/pubkeyhash/input.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/pubkeyhash/input'>;
}
declare module 'bitcoinjs-lib/src/templates/pubkeyhash/output.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/pubkeyhash/output'>;
}
declare module 'bitcoinjs-lib/src/templates/scripthash/index.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/scripthash/index'>;
}
declare module 'bitcoinjs-lib/src/templates/scripthash/input.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/scripthash/input'>;
}
declare module 'bitcoinjs-lib/src/templates/scripthash/output.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/scripthash/output'>;
}
declare module 'bitcoinjs-lib/src/templates/witnesscommitment/index.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/witnesscommitment/index'>;
}
declare module 'bitcoinjs-lib/src/templates/witnesscommitment/output.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/witnesscommitment/output'>;
}
declare module 'bitcoinjs-lib/src/templates/witnesspubkeyhash/index.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/witnesspubkeyhash/index'>;
}
declare module 'bitcoinjs-lib/src/templates/witnesspubkeyhash/input.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/witnesspubkeyhash/input'>;
}
declare module 'bitcoinjs-lib/src/templates/witnesspubkeyhash/output.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/witnesspubkeyhash/output'>;
}
declare module 'bitcoinjs-lib/src/templates/witnessscripthash/index.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/witnessscripthash/index'>;
}
declare module 'bitcoinjs-lib/src/templates/witnessscripthash/input.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/witnessscripthash/input'>;
}
declare module 'bitcoinjs-lib/src/templates/witnessscripthash/output.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/templates/witnessscripthash/output'>;
}
declare module 'bitcoinjs-lib/src/transaction_builder.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/transaction_builder'>;
}
declare module 'bitcoinjs-lib/src/transaction.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/transaction'>;
}
declare module 'bitcoinjs-lib/src/types.js' {
  declare module.exports: $Exports<'bitcoinjs-lib/src/types'>;
}
