// flow-typed signature: a2f67a2948b4013e32cd682a29a10bd6
// flow-typed version: <<STUB>>/bitcoinjs-message_v^2.0.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bitcoinjs-message'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bitcoinjs-message' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'bitcoinjs-message/index' {
  declare module.exports: $Exports<'bitcoinjs-message'>;
}
declare module 'bitcoinjs-message/index.js' {
  declare module.exports: $Exports<'bitcoinjs-message'>;
}
