// flow-typed signature: a61fde27c2d20c8fa1ec827031aa3f9c
// flow-typed version: <<STUB>>/bitcoin-sfox-client_v^0.2.6/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bitcoin-sfox-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bitcoin-sfox-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bitcoin-sfox-client/karma.conf' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/lib/api' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/lib/bank-link' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/lib/index' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/lib/payment-account' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/lib/payment-medium' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/lib/profile' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/lib/quote' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/lib/sfox' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/lib/trade' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/src/api' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/src/bank-link' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/src/index' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/src/payment-account' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/src/payment-medium' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/src/profile' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/src/quote' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/src/sfox' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/src/trade' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/tests/bank_link_spec' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/tests/payment_account_spec' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/tests/payment_medium_spec' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/tests/profile_spec' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/tests/quote_spec' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/tests/sfox_api_spec' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/tests/sfox_spec' {
  declare module.exports: any;
}

declare module 'bitcoin-sfox-client/tests/trade_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bitcoin-sfox-client/karma.conf.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/karma.conf'>;
}
declare module 'bitcoin-sfox-client/lib/api.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/lib/api'>;
}
declare module 'bitcoin-sfox-client/lib/bank-link.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/lib/bank-link'>;
}
declare module 'bitcoin-sfox-client/lib/index.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/lib/index'>;
}
declare module 'bitcoin-sfox-client/lib/payment-account.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/lib/payment-account'>;
}
declare module 'bitcoin-sfox-client/lib/payment-medium.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/lib/payment-medium'>;
}
declare module 'bitcoin-sfox-client/lib/profile.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/lib/profile'>;
}
declare module 'bitcoin-sfox-client/lib/quote.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/lib/quote'>;
}
declare module 'bitcoin-sfox-client/lib/sfox.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/lib/sfox'>;
}
declare module 'bitcoin-sfox-client/lib/trade.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/lib/trade'>;
}
declare module 'bitcoin-sfox-client/src/api.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/src/api'>;
}
declare module 'bitcoin-sfox-client/src/bank-link.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/src/bank-link'>;
}
declare module 'bitcoin-sfox-client/src/index.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/src/index'>;
}
declare module 'bitcoin-sfox-client/src/payment-account.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/src/payment-account'>;
}
declare module 'bitcoin-sfox-client/src/payment-medium.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/src/payment-medium'>;
}
declare module 'bitcoin-sfox-client/src/profile.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/src/profile'>;
}
declare module 'bitcoin-sfox-client/src/quote.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/src/quote'>;
}
declare module 'bitcoin-sfox-client/src/sfox.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/src/sfox'>;
}
declare module 'bitcoin-sfox-client/src/trade.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/src/trade'>;
}
declare module 'bitcoin-sfox-client/tests/bank_link_spec.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/tests/bank_link_spec'>;
}
declare module 'bitcoin-sfox-client/tests/payment_account_spec.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/tests/payment_account_spec'>;
}
declare module 'bitcoin-sfox-client/tests/payment_medium_spec.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/tests/payment_medium_spec'>;
}
declare module 'bitcoin-sfox-client/tests/profile_spec.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/tests/profile_spec'>;
}
declare module 'bitcoin-sfox-client/tests/quote_spec.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/tests/quote_spec'>;
}
declare module 'bitcoin-sfox-client/tests/sfox_api_spec.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/tests/sfox_api_spec'>;
}
declare module 'bitcoin-sfox-client/tests/sfox_spec.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/tests/sfox_spec'>;
}
declare module 'bitcoin-sfox-client/tests/trade_spec.js' {
  declare module.exports: $Exports<'bitcoin-sfox-client/tests/trade_spec'>;
}
