// flow-typed signature: e10c030c46c75eaa732ed29b0b73487b
// flow-typed version: <<STUB>>/daggy_v^1.2.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'daggy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'daggy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'daggy/src/daggy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'daggy/src/daggy.js' {
  declare module.exports: $Exports<'daggy/src/daggy'>;
}
