// flow-typed signature: 7cf0674d8b30fa78b0337016219958c0
// flow-typed version: <<STUB>>/ethereumjs-util_v^5.1.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethereumjs-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethereumjs-util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ethereumjs-util/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ethereumjs-util/dist/index.js' {
  declare module.exports: $Exports<'ethereumjs-util/dist/index'>;
}
