// flow-typed signature: 246756c0bc7ae9762218583ae5a05f60
// flow-typed version: <<STUB>>/extendable-immutable_v^1.3.3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extendable-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extendable-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extendable-immutable/es/extendable' {
  declare module.exports: any;
}

declare module 'extendable-immutable/es/index' {
  declare module.exports: any;
}

declare module 'extendable-immutable/es/List' {
  declare module.exports: any;
}

declare module 'extendable-immutable/es/Map' {
  declare module.exports: any;
}

declare module 'extendable-immutable/es/OrderedMap' {
  declare module.exports: any;
}

declare module 'extendable-immutable/es/OrderedSet' {
  declare module.exports: any;
}

declare module 'extendable-immutable/es/Set' {
  declare module.exports: any;
}

declare module 'extendable-immutable/es/Stack' {
  declare module.exports: any;
}

declare module 'extendable-immutable/es/util/createExtendable' {
  declare module.exports: any;
}

declare module 'extendable-immutable/es/util/startsWith' {
  declare module.exports: any;
}

declare module 'extendable-immutable/lib/extendable' {
  declare module.exports: any;
}

declare module 'extendable-immutable/lib/index' {
  declare module.exports: any;
}

declare module 'extendable-immutable/lib/List' {
  declare module.exports: any;
}

declare module 'extendable-immutable/lib/Map' {
  declare module.exports: any;
}

declare module 'extendable-immutable/lib/OrderedMap' {
  declare module.exports: any;
}

declare module 'extendable-immutable/lib/OrderedSet' {
  declare module.exports: any;
}

declare module 'extendable-immutable/lib/Set' {
  declare module.exports: any;
}

declare module 'extendable-immutable/lib/Stack' {
  declare module.exports: any;
}

declare module 'extendable-immutable/lib/util/createExtendable' {
  declare module.exports: any;
}

declare module 'extendable-immutable/lib/util/startsWith' {
  declare module.exports: any;
}

declare module 'extendable-immutable/src/extendable' {
  declare module.exports: any;
}

declare module 'extendable-immutable/src/index' {
  declare module.exports: any;
}

declare module 'extendable-immutable/src/List' {
  declare module.exports: any;
}

declare module 'extendable-immutable/src/Map' {
  declare module.exports: any;
}

declare module 'extendable-immutable/src/OrderedMap' {
  declare module.exports: any;
}

declare module 'extendable-immutable/src/OrderedSet' {
  declare module.exports: any;
}

declare module 'extendable-immutable/src/Set' {
  declare module.exports: any;
}

declare module 'extendable-immutable/src/Stack' {
  declare module.exports: any;
}

declare module 'extendable-immutable/src/util/createExtendable' {
  declare module.exports: any;
}

declare module 'extendable-immutable/src/util/startsWith' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extendable-immutable/es/extendable.js' {
  declare module.exports: $Exports<'extendable-immutable/es/extendable'>;
}
declare module 'extendable-immutable/es/index.js' {
  declare module.exports: $Exports<'extendable-immutable/es/index'>;
}
declare module 'extendable-immutable/es/List.js' {
  declare module.exports: $Exports<'extendable-immutable/es/List'>;
}
declare module 'extendable-immutable/es/Map.js' {
  declare module.exports: $Exports<'extendable-immutable/es/Map'>;
}
declare module 'extendable-immutable/es/OrderedMap.js' {
  declare module.exports: $Exports<'extendable-immutable/es/OrderedMap'>;
}
declare module 'extendable-immutable/es/OrderedSet.js' {
  declare module.exports: $Exports<'extendable-immutable/es/OrderedSet'>;
}
declare module 'extendable-immutable/es/Set.js' {
  declare module.exports: $Exports<'extendable-immutable/es/Set'>;
}
declare module 'extendable-immutable/es/Stack.js' {
  declare module.exports: $Exports<'extendable-immutable/es/Stack'>;
}
declare module 'extendable-immutable/es/util/createExtendable.js' {
  declare module.exports: $Exports<'extendable-immutable/es/util/createExtendable'>;
}
declare module 'extendable-immutable/es/util/startsWith.js' {
  declare module.exports: $Exports<'extendable-immutable/es/util/startsWith'>;
}
declare module 'extendable-immutable/lib/extendable.js' {
  declare module.exports: $Exports<'extendable-immutable/lib/extendable'>;
}
declare module 'extendable-immutable/lib/index.js' {
  declare module.exports: $Exports<'extendable-immutable/lib/index'>;
}
declare module 'extendable-immutable/lib/List.js' {
  declare module.exports: $Exports<'extendable-immutable/lib/List'>;
}
declare module 'extendable-immutable/lib/Map.js' {
  declare module.exports: $Exports<'extendable-immutable/lib/Map'>;
}
declare module 'extendable-immutable/lib/OrderedMap.js' {
  declare module.exports: $Exports<'extendable-immutable/lib/OrderedMap'>;
}
declare module 'extendable-immutable/lib/OrderedSet.js' {
  declare module.exports: $Exports<'extendable-immutable/lib/OrderedSet'>;
}
declare module 'extendable-immutable/lib/Set.js' {
  declare module.exports: $Exports<'extendable-immutable/lib/Set'>;
}
declare module 'extendable-immutable/lib/Stack.js' {
  declare module.exports: $Exports<'extendable-immutable/lib/Stack'>;
}
declare module 'extendable-immutable/lib/util/createExtendable.js' {
  declare module.exports: $Exports<'extendable-immutable/lib/util/createExtendable'>;
}
declare module 'extendable-immutable/lib/util/startsWith.js' {
  declare module.exports: $Exports<'extendable-immutable/lib/util/startsWith'>;
}
declare module 'extendable-immutable/src/extendable.js' {
  declare module.exports: $Exports<'extendable-immutable/src/extendable'>;
}
declare module 'extendable-immutable/src/index.js' {
  declare module.exports: $Exports<'extendable-immutable/src/index'>;
}
declare module 'extendable-immutable/src/List.js' {
  declare module.exports: $Exports<'extendable-immutable/src/List'>;
}
declare module 'extendable-immutable/src/Map.js' {
  declare module.exports: $Exports<'extendable-immutable/src/Map'>;
}
declare module 'extendable-immutable/src/OrderedMap.js' {
  declare module.exports: $Exports<'extendable-immutable/src/OrderedMap'>;
}
declare module 'extendable-immutable/src/OrderedSet.js' {
  declare module.exports: $Exports<'extendable-immutable/src/OrderedSet'>;
}
declare module 'extendable-immutable/src/Set.js' {
  declare module.exports: $Exports<'extendable-immutable/src/Set'>;
}
declare module 'extendable-immutable/src/Stack.js' {
  declare module.exports: $Exports<'extendable-immutable/src/Stack'>;
}
declare module 'extendable-immutable/src/util/createExtendable.js' {
  declare module.exports: $Exports<'extendable-immutable/src/util/createExtendable'>;
}
declare module 'extendable-immutable/src/util/startsWith.js' {
  declare module.exports: $Exports<'extendable-immutable/src/util/startsWith'>;
}
