// flow-typed signature: fe575d299d9196ed8d1d7db77400864e
// flow-typed version: <<STUB>>/fisher-yates_v^1.0.3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fisher-yates'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fisher-yates' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fisher-yates/inplace' {
  declare module.exports: any;
}

declare module 'fisher-yates/mutable' {
  declare module.exports: any;
}

declare module 'fisher-yates/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fisher-yates/index' {
  declare module.exports: $Exports<'fisher-yates'>;
}
declare module 'fisher-yates/index.js' {
  declare module.exports: $Exports<'fisher-yates'>;
}
declare module 'fisher-yates/inplace.js' {
  declare module.exports: $Exports<'fisher-yates/inplace'>;
}
declare module 'fisher-yates/mutable.js' {
  declare module.exports: $Exports<'fisher-yates/mutable'>;
}
declare module 'fisher-yates/test/index.js' {
  declare module.exports: $Exports<'fisher-yates/test/index'>;
}
