// flow-typed signature: 898ee58ce0251c5e210a4909ab26c71e
// flow-typed version: <<STUB>>/futurize_v^1.2.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'futurize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'futurize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'futurize/index' {
  declare module.exports: $Exports<'futurize'>;
}
declare module 'futurize/index.js' {
  declare module.exports: $Exports<'futurize'>;
}
