// flow-typed signature: cf4d65a4d55a8516e3d4e5d98aa55180
// flow-typed version: <<STUB>>/pbkdf2_v~3.0.12/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pbkdf2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pbkdf2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pbkdf2/browser' {
  declare module.exports: any;
}

declare module 'pbkdf2/lib/async' {
  declare module.exports: any;
}

declare module 'pbkdf2/lib/default-encoding' {
  declare module.exports: any;
}

declare module 'pbkdf2/lib/precondition' {
  declare module.exports: any;
}

declare module 'pbkdf2/lib/sync-browser' {
  declare module.exports: any;
}

declare module 'pbkdf2/lib/sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pbkdf2/browser.js' {
  declare module.exports: $Exports<'pbkdf2/browser'>;
}
declare module 'pbkdf2/index' {
  declare module.exports: $Exports<'pbkdf2'>;
}
declare module 'pbkdf2/index.js' {
  declare module.exports: $Exports<'pbkdf2'>;
}
declare module 'pbkdf2/lib/async.js' {
  declare module.exports: $Exports<'pbkdf2/lib/async'>;
}
declare module 'pbkdf2/lib/default-encoding.js' {
  declare module.exports: $Exports<'pbkdf2/lib/default-encoding'>;
}
declare module 'pbkdf2/lib/precondition.js' {
  declare module.exports: $Exports<'pbkdf2/lib/precondition'>;
}
declare module 'pbkdf2/lib/sync-browser.js' {
  declare module.exports: $Exports<'pbkdf2/lib/sync-browser'>;
}
declare module 'pbkdf2/lib/sync.js' {
  declare module.exports: $Exports<'pbkdf2/lib/sync'>;
}
