// flow-typed signature: 0020e2216a5ffa4d2e9bdf4d01cb580b
// flow-typed version: <<STUB>>/read-blob_v~1.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'read-blob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'read-blob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'read-blob/dist/read-blob' {
  declare module.exports: any;
}

// Filename aliases
declare module 'read-blob/dist/read-blob.js' {
  declare module.exports: $Exports<'read-blob/dist/read-blob'>;
}
declare module 'read-blob/index' {
  declare module.exports: $Exports<'read-blob'>;
}
declare module 'read-blob/index.js' {
  declare module.exports: $Exports<'read-blob'>;
}
