export const FETCH_METADATA_ETHEREUM = '@CORE.FETCH_METADATA_ETHEREUM'
export const FETCH_METADATA_ETHEREUM_LOADING =
  '@CORE.FETCH_METADATA_ETHEREUM_LOADING'
export const FETCH_METADATA_ETHEREUM_SUCCESS =
  '@CORE.FETCH_METADATA_ETHEREUM_SUCCESS'
export const FETCH_METADATA_ETHEREUM_FAILURE =
  '@CORE.FETCH_METADATA_ETHEREUM_FAILURE'

export const UPDATE_METADATA_ETHEREUM = '@CORE.KVSTORE.UPDATE_METADATA_ETHEREUM'

export const CREATE_METADATA_ETHEREUM = '@CORE.CREATE_METADATA_ETHEREUM'

export const SET_TRANSACTION_NOTE_ETHEREUM =
  '@CORE.SET_TRANSACTION_NOTE_ETHEREUM'

export const SET_TRANSACTION_NOTE_ERC20 = '@CORE.SET_TRANSACTION_NOTE_ERC20'

export const SET_LATEST_TX_ETHEREUM = '@CORE.SET_LATEST_TX_ETHEREUM'
export const SET_LATEST_TX_TIMESTAMP_ETHEREUM =
  '@CORE.SET_LATEST_TX_TIMESTAMP_ETHEREUM'
