export const FETCH_SETTINGS = '@CORE.FETCH_SETTINGS'
export const FETCH_SETTINGS_SUCCESS = '@CORE.FETCH_SETTINGS_SUCCESS'
export const FETCH_SETTINGS_ERROR = '@CORE.FETCH_SETTINGS_ERROR'

export const REQUEST_PAIRING_CODE = '@CORE.REQUEST_PAIRING_CODE'
export const REQUEST_PAIRING_CODE_SUCCESS = '@CORE.REQUEST_PAIRING_CODE_SUCCESS'
export const REQUEST_PAIRING_CODE_ERROR = '@CORE.REQUEST_PAIRING_CODE_ERROR'

export const UPDATE_EMAIL = '@CORE.UPDATE_EMAIL'
export const UPDATE_EMAIL_SUCCESS = '@CORE.UPDATE_EMAIL_SUCCESS'
export const UPDATE_EMAIL_ERROR = '@CORE.UPDATE_EMAIL_ERROR'

export const SEND_EMAIL_CONFIRMATION = '@CORE.SEND_EMAIL_CONFIRMATION'
export const SEND_EMAIL_CONFIRMATION_SUCCESS = '@CORE.SEND_EMAIL_CONFIRMATION_SUCCESS'
export const SEND_EMAIL_CONFIRMATION_ERROR = '@CORE.SEND_EMAIL_CONFIRMATION_ERROR'

export const VERIFY_EMAIL = '@CORE.VERIFY_EMAIL'
export const VERIFY_EMAIL_SUCCESS = '@CORE.VERIFY_EMAIL_SUCCESS'
export const VERIFY_EMAIL_ERROR = '@CORE.VERIFY_EMAIL_ERROR'

export const UPDATE_MOBILE = '@CORE.UPDATE_MOBILE'
export const UPDATE_MOBILE_SUCCESS = '@CORE.UPDATE_MOBILE_SUCCESS'
export const UPDATE_MOBILE_ERROR = '@CORE.UPDATE_MOBILE_ERROR'

export const VERIFY_MOBILE = '@CORE.VERIFY_MOBILE'
export const VERIFY_MOBILE_SUCCESS = '@CORE.VERIFY_MOBILE_SUCCESS'
export const VERIFY_MOBILE_ERROR = '@CORE.VERIFY_MOBILE_ERROR'
