export const dataPath = 'dataPath'
export const walletPath = 'walletPath'
export const kvStorePath = 'kvStorePath'
export const settingsPath = 'settingsPath'
export const walletOptionsPath = 'walletOptionsPath'
