export const UPDATE_METADATA_ROOT = '@CORE.KVSTORE.UPDATE_METADATA_ROOT'

// FETCH_METADATA_ROOT
export const FETCH_METADATA_ROOT = '@CORE.FETCH_METADATA_ROOT'
export const FETCH_METADATA_ROOT_LOADING = '@CORE.FETCH_METADATA_ROOT_LOADING'
export const FETCH_METADATA_ROOT_SUCCESS = '@CORE.FETCH_METADATA_ROOT_SUCCESS'
export const FETCH_METADATA_ROOT_FAILURE = '@CORE.FETCH_METADATA_ROOT_FAILURE'
