// CREATE
export const CREATE_METADATA_LOCKBOX = '@CORE.CREATE_METADATA_LOCKBOX'

// FETCH
export const FETCH_METADATA_LOCKBOX = '@CORE.FETCH_METADATA_LOCKBOX'
export const FETCH_METADATA_LOCKBOX_LOADING =
  '@CORE.FETCH_METADATA_LOCKBOX_LOADING'
export const FETCH_METADATA_LOCKBOX_SUCCESS =
  '@CORE.FETCH_METADATA_LOCKBOX_SUCCESS'
export const FETCH_METADATA_LOCKBOX_FAILURE =
  '@CORE.FETCH_METADATA_LOCKBOX_FAILURE'

// UPDATE
export const STORE_DEVICE_NAME = '@CORE.STORE_DEVICE_NAME'
export const STORE_DEVICE_BACKUP_FLAG = '@CORE.STORE_DEVICE_BACKUP_FLAG'
export const STORE_DEVICE_ACCOUNTS = '@CORE.STORE_DEVICE_ACCOUNTS'

// DELETE
export const DELETE_DEVICE_LOCKBOX = '@CORE.DELETE_DEVICE_LOCKBOX'
