export const FETCH_METADATA_LOCKBOX = '@CORE.FETCH_METADATA_LOCKBOX'
export const FETCH_METADATA_LOCKBOX_LOADING = '@CORE.FETCH_METADATA_LOCKBOX_LOADING'
export const FETCH_METADATA_LOCKBOX_SUCCESS = '@CORE.FETCH_METADATA_LOCKBOX_SUCCESS'
export const FETCH_METADATA_LOCKBOX_FAILURE = '@CORE.FETCH_METADATA_LOCKBOX_FAILURE'
