// CREATE
export const CREATE_METADATA_LOCKBOX = '@CORE.CREATE_METADATA_LOCKBOX'
export const CREATE_NEW_DEVICE_ENTRY = '@CORE.CREATE_NEW_DEVICE_ENTRY'

// FETCH
export const FETCH_METADATA_LOCKBOX = '@CORE.FETCH_METADATA_LOCKBOX'
export const FETCH_METADATA_LOCKBOX_LOADING =
  '@CORE.FETCH_METADATA_LOCKBOX_LOADING'
export const FETCH_METADATA_LOCKBOX_SUCCESS =
  '@CORE.FETCH_METADATA_LOCKBOX_SUCCESS'
export const FETCH_METADATA_LOCKBOX_FAILURE =
  '@CORE.FETCH_METADATA_LOCKBOX_FAILURE'

// UPDATE
export const UPDATE_DEVICE_BALANCE_DISPLAY =
  '@CORE.UPDATE_DEVICE_BALANCE_DISPLAY'
export const ADD_COIN_ENTRY = '@CORE.ADD_COIN_ENTRY'
export const UPDATE_DEVICE_NAME = '@CORE.UPDATE_DEVICE_NAME'
export const SET_LATEST_TX_ETH_LOCKBOX = '@CORE.SET_LATEST_TX_ETH_LOCKBOX'
export const SET_LATEST_TX_TIMESTAMP_ETH_LOCKBOX =
  '@CORE.SET_LATEST_TX_TIMESTAMP_ETH_LOCKBOX'

// DELETE
export const DELETE_DEVICE_LOCKBOX = '@CORE.DELETE_DEVICE_LOCKBOX'
