// FETCH_METADATA_XLM
export const FETCH_METADATA_XLM = '@CORE.FETCH_METADATA_XLM'
export const FETCH_METADATA_XLM_LOADING = '@CORE.FETCH_METADATA_XLM_LOADING'
export const FETCH_METADATA_XLM_SUCCESS = '@CORE.FETCH_METADATA_XLM_SUCCESS'
export const FETCH_METADATA_XLM_FAILURE = '@CORE.FETCH_METADATA_XLM_FAILURE'

// UPDATE_METADATA_XLM
export const UPDATE_METADATA_XLM = '@CORE.KVSTORE.UPDATE_METADATA_XLM'

// CREATE_METADATA_XLM
export const CREATE_METADATA_XLM = '@CORE.CREATE_METADATA_XLM'

export const SET_TRANSACTION_NOTE_XLM = '@CORE.SET_TRANSACTION_NOTE_XLM'
