// Actions caught by reducer
export const TRANSACTION_CONFIRMED = '@LN.BLOCKCHAIN.TRANSACTION_CONFIRMED'
export const TRANSACTION_PUSHED = '@LN.BLOCKCHAIN.TRANSACTION_PUSHED'
export const  ADD_TRANSACTION= '@LN.BLOCKCHAIN.ADD_TRANSACTION'

// Actions caught by sagas
export const  PUSH_TRANSACTION= '@LN.BLOCKCHAIN.ADD_TRANSACTION'

