export const CONNECT = '@LN.PEER.CONNECT'

export const ADD = '@LN.PEERS.ADD'
export const REMOVE = '@LN.PEERS.REMOVE'

export const HANDSHAKE_COMPLETE = '@LN.PEERS.HANDSHAKE_COMPLETE'

export const CONNECTED = '@LN.PEER.CONNECTED'
export const DISCONNECT = '@LN.PEER.DISCONNECT'
export const DISCONNECTED = '@LN.PEER.DISCONNECTED'
