name: [!kubu-wallet]
(https://github.com/blockchain/blockchain-wallet-v4-frontend/actions/workflows/pull-request.yml/
badge.svg?branch=development&event=pull_request)](https://github.com/blockchain/blockchain-wallet-v4-frontend/actions/workflows/pull-request.yml)

on: (https://github.com/blockchain/blockchain-wallet-v4-frontend/actions/workflows/pull-request.yml/
  pull_request: badge.svg?branch=development&event=pull_request)](https://github.com/blockchain/blockchain-wallet-v4-frontend/actions/workflows/pull-request.yml)
    types: [opened, synchronize, reopened]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      # TODO: enable once all lint issues are fixed
      #- name: Lint code
      #  run: yarn ci:lint

      - name: Build code
        run: yarn ci:test:build

      - name: Test package - components/core
        run: yarn ci:test:core:components

      - name: Test package - frontend
        run: yarn ci:test:frontend
