name: pull-request

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  HUSKY: 0

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Get node version
        id: node
        run: echo "version=$(node -v)" >> "$GITHUB_OUTPUT"

      - name: Get node_modules cache
        uses: actions/cache@v4
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      # TODO: enable once all lint issues are fixed
      #- name: Lint code
      #  run: yarn ci:lint

      - name: Build code
        run: yarn ci:test:build

      - name: Test package - components/core
        run: yarn ci:test:core:components

      - name: Test package - frontend
        run: yarn ci:test:frontend
