name: pull-request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      # TODO: enable once all lint issues are fixed
      #- name: Lint code
      #  run: yarn ci:lint

      - name: Build code
        run: yarn ci:test:build

      - name: Test package - components/core
        run: yarn ci:test:core:components

      - name: Test package - frontend
        run: yarn ci:test:frontend