// FETCH_METADATA_BTC
export const FETCH_METADATA_BTC = '@CORE.FETCH_METADATA_BTC'
export const FETCH_METADATA_BTC_LOADING = '@CORE.FETCH_METADATA_BTC_LOADING'
export const FETCH_METADATA_BTC_SUCCESS = '@CORE.FETCH_METADATA_BTC_SUCCESS'
export const FETCH_METADATA_BTC_FAILURE = '@CORE.FETCH_METADATA_BTC_FAILURE'

export const CREATE_METADATA_BTC = '@CORE.CREATE_METADATA_BTC'

export const ADD_ADDRESS_LABEL = '@CORE.ADD_ADDRESS_LABEL'
